# server port
# server.port=8082
server:
  port: 8084

# data base
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_reservation?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user_reservation
    password: 1234

    # i'mport 결제 api 키 관리
import:
  apiKey:
  secretKey:

  # thymeleaf
  thymeleaf:
    cache: false

  # spring data jpa
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: update

  web:
    resources:
      static-locations:
        - 'file:/C:/springboot_reviewImg/'
        - 'classpath:/static/'

# db query log
logging:
  level:
    org:
      hibernate:
        SQL: trace
        type:
          descriptor:
            sql:
              BasicBinder: trace
